# Generated by Django 5.1.4 on 2025-01-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Username', models.CharField(default='', max_length=5)),
                ('Password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
