# Generated by Django 5.1.4 on 2025-01-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EName', models.CharField(default='', max_length=50)),
                ('Mail', models.CharField(default='', max_length=50)),
                ('YourMessage', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
