# Generated by Django 5.1.6 on 2025-02-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0003_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('CarBrand', models.CharField(default='carname', max_length=50)),
                ('ModelName', models.CharField(default='modelname', max_length=50)),
                ('phone', models.CharField(default='91', max_length=10)),
                ('date', models.DateField()),
                ('address', models.CharField(default='', max_length=300)),
                ('service_category', models.CharField(choices=[('1', 'General Service'), ('2', 'Painting Service'), ('3', 'AC Service'), ('4', 'Detailing Service'), ('5', 'Custom Repair Service'), ('6', 'Insurance')], default='service category', max_length=10)),
                ('pickup_slot', models.IntegerField(choices=[(1, '10.00am-1.00pm'), (2, '3.00pm-5.00pm')], default='select time pickup slot')),
                ('package', models.CharField(blank=True, max_length=255, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'pickup_slot'), name='unique_booking_per_slot')],
            },
        ),
    ]
